# This file has been automatically generated by Cheetah: edit the corresponding
# template instead of changing it.

export AFDSMGRD_PROG="/home/sysman/devel/afdsmgrd/production/bin"/afdsmgrd
export AFDSMGRD_CONF="/opt/aaf/etc/proof/afdsmgrd.conf"
export ROOTSYS="/opt/alicesw/packages/VO_ALICE/ROOT/v5-34-04/v5-34-04"
export AFDSMGRD_LIBS="/opt/alicesw/packages/alien/api/lib"
export AFDSMGRD_LIBEXEC="/home/sysman/devel/afdsmgrd/production/libexec"
export AFDSMGRD_LOGDIR="/opt/aaf/var/log/afdsmgrd"
export AFDSMGRD_LOGFILE="$AFDSMGRD_LOGDIR/afdsmgrd.log"
export AFDSMGRD_PIDFILE="/opt/aaf"/var/run/afdsmgrd.pid
export AFDSMGRD_USER="sysman"
export AFDSMGRD_GROUP="wheel"
export AFDSMGRD_LOGLEVEL=low
