# This file has been automatically generated by Cheetah! It is pointless to edit
# it, edit the template or /etc/aafrc instead!

use lib "/opt/aaf/lib/perl-apmon";

our $masterHost = "pmaster.to.infn.it";
our $proofConnectAlias = "pmaster.to.infn.it";
our $apMonClusterPrefix = "PROOF::TAF::STORAGE";
our $apMonHostPort = "193.206.184.59:8884";
our $apStatus = "Stable";
our $apRootVer = basename("/opt/alicesw/packages/VO_ALICE/ROOT/v5-34-04/v5-34-04");
our $storagePath = "/storage";
